version: '3'
services:
  web:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./target:/app
      - ./script/:/sh
    command: /sh/wait-for-it.sh db:5432 -- /sh/wait-for-it.sh redis:6379 -- java -jar -Dspring.profiles.active=container /app/bot-1.0.jar
    ports:
      - "80:8080"
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: sameersbn/postgresql:9.6-2
    expose: ["5432"]
    restart: always
    environment:
     DB_USER: "docker"
     DB_PASS: "docker"
     DB_NAME: "test"
    volumes:
    - /srv/docker/postgresql:/var/lib/postgresql
    - ./src/main/resources/data:/docker-entrypoint-initdb.d
  redis:
    image: redis
    
